# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-29 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('prev_price', models.FloatField(blank=True, default=0, null=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'CarPrice',
            },
        ),
    ]
